// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members, combinators_ordering, no_default_cases
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1V4aOkYoIWXqOwhDGlFqLyZyQZT_8ktg',
    appId: '1:901012641158:web:3990f115441ebb511f4807',
    messagingSenderId: '901012641158',
    projectId: 'fca-education-app-bloc',
    authDomain: 'fca-education-app-bloc.firebaseapp.com',
    storageBucket: 'fca-education-app-bloc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPtFS9c_BVV0NV52cZN0h9J9Y_ahYyJRA',
    appId: '1:901012641158:android:aca011b4cc6038621f4807',
    messagingSenderId: '901012641158',
    projectId: 'fca-education-app-bloc',
    storageBucket: 'fca-education-app-bloc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCALqYb5bEw1-W7fZOL2G9_QKEyf7EzWg',
    appId: '1:901012641158:ios:07f57f8b6f505fd41f4807',
    messagingSenderId: '901012641158',
    projectId: 'fca-education-app-bloc',
    storageBucket: 'fca-education-app-bloc.appspot.com',
    iosBundleId: 'com.example.fcaEducationApp',
  );
}
